In [2]:
import pandas as pd

In [3]:
df2 = pd.read_csv('/Users/bayerd01/Documents/ML CITIES/Housing_Maintenance_Code_Violations.csv')

df2

/Users/bayerd01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (10,23) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,ViolationStatus,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA
0,10000197,74898,205177,2,BRONX,231,231,231,ECHO PLACE,29920,...,Open,N,40.849718,-73.904550,5.0,15.0,23502.0,2007730.0,2.028100e+09,Mount Hope
1,10000355,96334,218008,2,BRONX,2913,2913,2913,MIDDLETOWN ROAD,50920,...,Close,Y,40.843576,-73.832520,10.0,13.0,26602.0,2045974.0,2.041650e+09,Pelham Bay-Country Club-City Island
2,10000419,63911,208491,2,BRONX,109,109,109,EAST 153 STREET,26250,...,Close,N,40.823932,-73.928033,4.0,8.0,63.0,2002968.0,2.024820e+09,West Concourse
3,12838207,115654,205456,2,BRONX,1565,1565,1565,TOWNSEND AVENUE,69320,...,Close,N,40.843427,-73.914263,4.0,14.0,209.0,2008141.0,2.028460e+09,West Concourse
4,10000695,94086,207860,2,BRONX,1064,1064,1064,MANOR AVENUE,49020,...,Open,N,40.825543,-73.875585,9.0,18.0,48.0,2023565.0,2.037170e+09,Soundview-Bruckner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249831,9099739,287222,305039,3,BROOKLYN,1352,1352,1352,EAST NEW YORK AVENUE,38330,...,Open,N,40.669409,-73.917425,16.0,41.0,902.0,3080699.0,3.034930e+09,Brownsville
7249832,9618104,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,Close,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North
7249833,9817995,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,Close,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North
7249834,9992701,597256,924789,4,QUEENS,115-07,115-07,115-07,208 STREET,26190,...,Open,N,40.699644,-73.745703,13.0,27.0,53401.0,4238025.0,4.110510e+09,Cambria Heights
7249835,9990191,13995,104724,1,MANHATTAN,300,300,300,EAST 50 STREET,17990,...,Close,N,40.754720,-73.968172,6.0,4.0,98.0,1080458.0,1.013420e+09,Turtle Bay-East Midtown

In [3]:
df2.columns

Index(['ViolationID', 'BuildingID', 'RegistrationID', 'BoroID', 'Borough',
       'HouseNumber', 'LowHouseNumber', 'HighHouseNumber', 'StreetName',
       'StreetCode', 'Postcode', 'Apartment', 'Story', 'Block', 'Lot', 'Class',
       'InspectionDate', 'ApprovedDate', 'OriginalCertifyByDate',
       'OriginalCorrectByDate', 'NewCertifyByDate', 'NewCorrectByDate',
       'CertifiedDate', 'OrderNumber', 'NOVID', 'NOVDescription',
       'NOVIssuedDate', 'CurrentStatusID', 'CurrentStatus',
       'CurrentStatusDate', 'NovType', 'ViolationStatus', 'RentImpairing',
       'Latitude', 'Longitude', 'CommunityBoard', 'CouncilDistrict',
       'CensusTract', 'BIN', 'BBL', 'NTA'],
      dtype='object')

In [46]:
max(df2['InspectionDate'])

Timestamp('2022-03-20 00:00:00')

In [4]:
#convert to datetime
df2['InspectionDate']= pd.to_datetime(df2['InspectionDate'], errors='coerce')

In [5]:
df2['year'] = df2['InspectionDate'].dt.year

In [50]:
df2['year'].unique()

array([2013, 2019, 2014, 2018, 2016, 2021, 1998, 1989, 1988, 2022, 1985,
       1993, 1994, 1997, 1992, 1982, 1991, 1987, 2004, 2017, 2015, 2005,
       1999, 1986, 1996, 1984, 1990, 2006, 2020, 2007, 2008, 1995, 2009,
       2010, 1983, 2011, 1978, 1975, 1981, 1979, 2012, 1977, 2000, 2002,
       2001, 2003, 1980, 1976, 1967, 1969, 1970, 1974, 1964, 1973, 1971,
       1972, 1903, 1966, 1930, 1968, 1963, 1919, 1965, 1960, 1933, 1961,
       1939, 1959, 1909])

In [6]:
#remove incorrect dates
years = [2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]

df2_2012_2022 = df2[df2.year.isin(years)]

df2_2012_2022

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,year
0,10000197,74898,205177,2,BRONX,231,231,231,ECHO PLACE,29920,...,N,40.849718,-73.904550,5.0,15.0,23502.0,2007730.0,2.028100e+09,Mount Hope,2013.0
1,10000355,96334,218008,2,BRONX,2913,2913,2913,MIDDLETOWN ROAD,50920,...,Y,40.843576,-73.832520,10.0,13.0,26602.0,2045974.0,2.041650e+09,Pelham Bay-Country Club-City Island,2013.0
2,10000419,63911,208491,2,BRONX,109,109,109,EAST 153 STREET,26250,...,N,40.823932,-73.928033,4.0,8.0,63.0,2002968.0,2.024820e+09,West Concourse,2013.0
3,12838207,115654,205456,2,BRONX,1565,1565,1565,TOWNSEND AVENUE,69320,...,N,40.843427,-73.914263,4.0,14.0,209.0,2008141.0,2.028460e+09,West Concourse,2019.0
4,10000695,94086,207860,2,BRONX,1064,1064,1064,MANOR AVENUE,49020,...,N,40.825543,-73.875585,9.0,18.0,48.0,2023565.0,2.037170e+09,Soundview-Bruckner,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249829,14997099,230367,360148,3,BROOKLYN,739,739,739,DE KALB AVENUE,31530,...,N,40.691917,-73.946746,3.0,36.0,261.0,3378134.0,3.017750e+09,Bedford,2022.0
7249832,9618104,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North,2012.0
7249833,9817995,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North,2013.0
7249834,9992701,597256,924789,4,QUEENS,115-07,115-07,115-07,208 STREET,26190,...,N,40.699644,-73.745703,13.0,27.0,53401.0,4238025.0,4.110510e+09,Cambria Heights,2013.0
7249835,9990191,13995,104724,1,MANHATTAN,300,300,300,EAST 50 STREET,17990,...,N,40.754720,-73.968172,6.0,4.0,98.0,1080458.0,1.013420e+09,Turtle Bay-East Midtown,2013.0

In [10]:
df2_2012_2022['CensusTract'].dtype

dtype('float64')

In [7]:
hpd_2012_2022 = df2_2012_2022.dropna(subset=['CensusTract'])

hpd_2012_2022

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,year
0,10000197,74898,205177,2,BRONX,231,231,231,ECHO PLACE,29920,...,N,40.849718,-73.904550,5.0,15.0,23502.0,2007730.0,2.028100e+09,Mount Hope,2013.0
1,10000355,96334,218008,2,BRONX,2913,2913,2913,MIDDLETOWN ROAD,50920,...,Y,40.843576,-73.832520,10.0,13.0,26602.0,2045974.0,2.041650e+09,Pelham Bay-Country Club-City Island,2013.0
2,10000419,63911,208491,2,BRONX,109,109,109,EAST 153 STREET,26250,...,N,40.823932,-73.928033,4.0,8.0,63.0,2002968.0,2.024820e+09,West Concourse,2013.0
3,12838207,115654,205456,2,BRONX,1565,1565,1565,TOWNSEND AVENUE,69320,...,N,40.843427,-73.914263,4.0,14.0,209.0,2008141.0,2.028460e+09,West Concourse,2019.0
4,10000695,94086,207860,2,BRONX,1064,1064,1064,MANOR AVENUE,49020,...,N,40.825543,-73.875585,9.0,18.0,48.0,2023565.0,2.037170e+09,Soundview-Bruckner,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249829,14997099,230367,360148,3,BROOKLYN,739,739,739,DE KALB AVENUE,31530,...,N,40.691917,-73.946746,3.0,36.0,261.0,3378134.0,3.017750e+09,Bedford,2022.0
7249832,9618104,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North,2012.0
7249833,9817995,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4.0,37.0,431.0,3075096.0,3.032890e+09,Bushwick North,2013.0
7249834,9992701,597256,924789,4,QUEENS,115-07,115-07,115-07,208 STREET,26190,...,N,40.699644,-73.745703,13.0,27.0,53401.0,4238025.0,4.110510e+09,Cambria Heights,2013.0
7249835,9990191,13995,104724,1,MANHATTAN,300,300,300,EAST 50 STREET,17990,...,N,40.754720,-73.968172,6.0,4.0,98.0,1080458.0,1.013420e+09,Turtle Bay-East Midtown,2013.0

In [8]:
#remove decimal values from community board, council district, census tract, year

hpd_2012_2022['CensusTract'] = hpd_2012_2022['CensusTract'].astype(int)
hpd_2012_2022['year'] = hpd_2012_2022['year'].astype(int)
hpd_2012_2022['CommunityBoard'] = hpd_2012_2022['CommunityBoard'].astype(int)
hpd_2012_2022['CouncilDistrict'] = hpd_2012_2022['CouncilDistrict'].astype(int)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1299523982.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['CensusTract'] = hpd_2012_2022['CensusTract'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1299523982.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['year'] = hpd_2012_2022['year'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1299523982.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['CommunityBoard'] = hpd_2012_2022['CommunityBoard'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1299523982.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['CouncilDistrict'] = hpd_2012_2022['CouncilDistrict'].astype(int)

In [9]:
hpd_2012_2022['BIN'] = hpd_2012_2022['BIN'].fillna(0)
hpd_2012_2022['BBL'] = hpd_2012_2022['BBL'].fillna(0)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1764346194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['BIN'] = hpd_2012_2022['BIN'].fillna(0)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1764346194.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['BBL'] = hpd_2012_2022['BBL'].fillna(0)

In [10]:
hpd_2012_2022['BIN'] = hpd_2012_2022['BIN'].astype(int)
hpd_2012_2022['BBL'] = hpd_2012_2022['BBL'].astype(int)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1906673667.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['BIN'] = hpd_2012_2022['BIN'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1906673667.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hpd_2012_2022['BBL'] = hpd_2012_2022['BBL'].astype(int)

In [11]:
hpd_2012_2022

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,year
0,10000197,74898,205177,2,BRONX,231,231,231,ECHO PLACE,29920,...,N,40.849718,-73.904550,5,15,23502,2007730,2028100045,Mount Hope,2013
1,10000355,96334,218008,2,BRONX,2913,2913,2913,MIDDLETOWN ROAD,50920,...,Y,40.843576,-73.832520,10,13,26602,2045974,2041650003,Pelham Bay-Country Club-City Island,2013
2,10000419,63911,208491,2,BRONX,109,109,109,EAST 153 STREET,26250,...,N,40.823932,-73.928033,4,8,63,2002968,2024820001,West Concourse,2013
3,12838207,115654,205456,2,BRONX,1565,1565,1565,TOWNSEND AVENUE,69320,...,N,40.843427,-73.914263,4,14,209,2008141,2028460041,West Concourse,2019
4,10000695,94086,207860,2,BRONX,1064,1064,1064,MANOR AVENUE,49020,...,N,40.825543,-73.875585,9,18,48,2023565,2037170032,Soundview-Bruckner,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249829,14997099,230367,360148,3,BROOKLYN,739,739,739,DE KALB AVENUE,31530,...,N,40.691917,-73.946746,3,36,261,3378134,3017750055,Bedford,2022
7249832,9618104,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4,37,431,3075096,3032890010,Bushwick North,2012
7249833,9817995,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4,37,431,3075096,3032890010,Bushwick North,2013
7249834,9992701,597256,924789,4,QUEENS,115-07,115-07,115-07,208 STREET,26190,...,N,40.699644,-73.745703,13,27,53401,4238025,4110510040,Cambria Heights,2013
7249835,9990191,13995,104724,1,MANHATTAN,300,300,300,EAST 50 STREET,17990,...,N,40.754720,-73.968172,6,4,98,1080458,1013420051,Turtle Bay-East Midtown,2013

In [11]:
hpd_2012_2022.columns

Index(['ViolationID', 'BuildingID', 'RegistrationID', 'BoroID', 'Borough',
       'HouseNumber', 'LowHouseNumber', 'HighHouseNumber', 'StreetName',
       'StreetCode', 'Postcode', 'Apartment', 'Story', 'Block', 'Lot', 'Class',
       'InspectionDate', 'ApprovedDate', 'OriginalCertifyByDate',
       'OriginalCorrectByDate', 'NewCertifyByDate', 'NewCorrectByDate',
       'CertifiedDate', 'OrderNumber', 'NOVID', 'NOVDescription',
       'NOVIssuedDate', 'CurrentStatusID', 'CurrentStatus',
       'CurrentStatusDate', 'NovType', 'ViolationStatus', 'RentImpairing',
       'Latitude', 'Longitude', 'CommunityBoard', 'CouncilDistrict',
       'CensusTract', 'BIN', 'BBL', 'NTA', 'year'],
      dtype='object')

In [38]:
#all hpd violations - date filtered

hpd_2012_2022.to_csv('hpd_2012_2022_v2.csv')

In [14]:
#FILTER OUT VACANCY ORDER NUMBERS

vac_orders= [614,630,631,632,765,766,767,768,1067,1068]


hpd_2012_2022_v2 = hpd_2012_2022[~hpd_2012_2022.OrderNumber.isin(vac_orders)]

hpd_2012_2022_v2

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,year
0,10000197,74898,205177,2,BRONX,231,231,231,ECHO PLACE,29920,...,N,40.849718,-73.904550,5,15,23502,2007730,2028100045,Mount Hope,2013
1,10000355,96334,218008,2,BRONX,2913,2913,2913,MIDDLETOWN ROAD,50920,...,Y,40.843576,-73.832520,10,13,26602,2045974,2041650003,Pelham Bay-Country Club-City Island,2013
2,10000419,63911,208491,2,BRONX,109,109,109,EAST 153 STREET,26250,...,N,40.823932,-73.928033,4,8,63,2002968,2024820001,West Concourse,2013
3,12838207,115654,205456,2,BRONX,1565,1565,1565,TOWNSEND AVENUE,69320,...,N,40.843427,-73.914263,4,14,209,2008141,2028460041,West Concourse,2019
4,10000695,94086,207860,2,BRONX,1064,1064,1064,MANOR AVENUE,49020,...,N,40.825543,-73.875585,9,18,48,2023565,2037170032,Soundview-Bruckner,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249829,14997099,230367,360148,3,BROOKLYN,739,739,739,DE KALB AVENUE,31530,...,N,40.691917,-73.946746,3,36,261,3378134,3017750055,Bedford,2022
7249832,9618104,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4,37,431,3075096,3032890010,Bushwick North,2012
7249833,9817995,307987,366570,3,BROOKLYN,290,290,290,HARMAN STREET,47330,...,N,40.699888,-73.918873,4,37,431,3075096,3032890010,Bushwick North,2013
7249834,9992701,597256,924789,4,QUEENS,115-07,115-07,115-07,208 STREET,26190,...,N,40.699644,-73.745703,13,27,53401,4238025,4110510040,Cambria Heights,2013
7249835,9990191,13995,104724,1,MANHATTAN,300,300,300,EAST 50 STREET,17990,...,N,40.754720,-73.968172,6,4,98,1080458,1013420051,Turtle Bay-East Midtown,2013

In [15]:
#all hpd violations - date and vacancy filtered

hpd_2012_2022_v2.to_csv('hpd_2012_2022_v3.csv')

In [18]:
# number of hpd violations per year
hpd_2012_2022_v2["year"].value_counts().sort_index()

2012    290291
2013    378255
2014    396220
2015    549140
2016    512432
2017    555909
2018    641448
2019    669111
2020    418930
2021    761228
2022    294104
Name: year, dtype: int64

In [20]:
#violations per bbl
hpd_per_bbl= hpd_2012_2022_v2["BBL"].value_counts().reset_index().rename({"index":"BBL", "BBL":"num_hpd_vio"}, axis = 1)
hpd_per_bbl

               BBL  num_hpd_vio
0       3042719001         6411
1                0         5450
2       2024310026         4818
3       5012720011         4170
4       3013020001         4075
...            ...          ...
181589  1019430052            1
181590  1012060017            1
181591  1018850049            1
181592  1012520050            1
181593  3011430042            1

[181594 rows x 2 columns]

In [28]:
# b & c violations per bbl
violations = ['C','B']

violations_b_c= hpd_2012_2022_v2[hpd_2012_2022_v2.Class.isin(violations)]

print(violations_b_c)

         ViolationID  BuildingID  RegistrationID  BoroID    Borough  \
1           10000355       96334          218008       2      BRONX
2           10000419       63911          208491       2      BRONX
3           12838207      115654          205456       2      BRONX
5           10000927       81720          208238       2      BRONX
6           10000932       81720          208238       2      BRONX
...              ...         ...             ...     ...        ...
7249829     14997099      230367          360148       3   BROOKLYN
7249832      9618104      307987          366570       3   BROOKLYN
7249833      9817995      307987          366570       3   BROOKLYN
7249834      9992701      597256          924789       4     QUEENS
7249835      9990191       13995          104724       1  MANHATTAN

        HouseNumber LowHouseNumber HighHouseNumber       StreetName  \
1              2913           2913            2913  MIDDLETOWN ROAD
2               109            109             109  EAST 153 STREET
3              1565           1565            1565  TOWNSEND AVENUE
5              1750           1750            1750  GRAND CONCOURSE
6              1750           1750            1750  GRAND CONCOURSE
...             ...            ...             ...              ...
7249829         739            739             739   DE KALB AVENUE
7249832         290            290             290    HARMAN STREET
7249833         290            290             290    HARMAN STREET
7249834      115-07         115-07          115-07       208 STREET
7249835         300            300             300   EAST 50 STREET

         StreetCode  ... RentImpairing   Latitude  Longitude  CommunityBoard  \
1             50920  ...             Y  40.843576 -73.832520              10
2             26250  ...             N  40.823932 -73.928033               4
3             69320  ...             N  40.843427 -73.914263               4
5             36420  ...             N  40.845765 -73.910292               5
6             36420  ...             N  40.845765 -73.910292               5
...             ...  ...           ...        ...        ...             ...
7249829       31530  ...             N  40.691917 -73.946746               3
7249832       47330  ...             N  40.699888 -73.918873               4
7249833       47330  ...             N  40.699888 -73.918873               4
7249834       26190  ...             N  40.699644 -73.745703              13
7249835       17990  ...             N  40.754720 -73.968172               6

         CouncilDistrict CensusTract      BIN         BBL  \
1                     13       26602  2045974  2041650003
2                      8          63  2002968  2024820001
3                     14         209  2008141  2028460041
5                     15       22901  2007875  2028250010
6                     15       22901  2007875  2028250010
...                  ...         ...      ...         ...
7249829               36         261  3378134  3017750055
7249832               37         431  3075096  3032890010
7249833               37         431  3075096  3032890010
7249834               27       53401  4238025  4110510040
7249835                4          98  1080458  1013420051

                                         NTA  year
1        Pelham Bay-Country Club-City Island  2013
2                             West Concourse  2013
3                             West Concourse  2019
5                                 Mount Hope  2013
6                                 Mount Hope  2013
...                                      ...   ...
7249829                              Bedford  2022
7249832                       Bushwick North  2012
7249833                       Bushwick North  2013
7249834                      Cambria Heights  2013
7249835              Turtle Bay-East Midtown  2013

[3717008 rows x 42 columns]

In [29]:
violations_b_c_per_bbl= violations_b_c["BBL"].value_counts().reset_index().rename({"index":"BBL", "BBL":"hpd_b_c_vio"}, axis = 1)

violations_b_c_per_bbl

              BBL  hpd_b_c_vio
0      3042719001         4898
1      2024310026         3712
2               0         3482
3      3013020001         3257
4      2037430063         3223
...           ...          ...
98941  1013730009            1
98942  4006970098            1
98943  4006970097            1
98944  3033280036            1
98945  3032000001            1

[98946 rows x 2 columns]

In [30]:
#fire code violations

#not sure if we want this as a separate variable
codes = [176,181,188, 213,222,483, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521,522,523,524,525,695, 696, 697, 698, 699,812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822]

fire_codes = hpd_2012_2022_v2[hpd_2012_2022_v2.OrderNumber.isin(codes)]

fire_codes

,ViolationID,BuildingID,RegistrationID,BoroID,Borough,HouseNumber,LowHouseNumber,HighHouseNumber,StreetName,StreetCode,...,RentImpairing,Latitude,Longitude,CommunityBoard,CouncilDistrict,CensusTract,BIN,BBL,NTA,year
19,10002544,42876,100595,1,MANHATTAN,560,558,560,WEST 160 STREET,36970,...,N,40.835397,-73.942262,12,7,245,1062785,1021180011,Washington Heights South,2013
35,10004884,81720,208238,2,BRONX,1750,1750,1750,GRAND CONCOURSE,36420,...,N,40.845765,-73.910292,5,15,22901,2007875,2028250010,Mount Hope,2013
49,10004912,60275,204782,2,BRONX,3230,3230,3230,CRUGER AVENUE,22920,...,N,40.872255,-73.866129,12,15,374,2056265,2045970021,Williamsbridge-Olinville,2013
168,10011504,356780,308812,3,BROOKLYN,1453,1453,1453,PROSPECT PLACE,72730,...,Y,40.673142,-73.928459,8,36,347,3036098,3013610056,Crown Heights North,2013
333,10025610,116930,202703,2,BRONX,2290,2290,2290,UNIVERSITY AVENUE,70620,...,Y,40.860671,-73.906801,7,14,253,2014595,2032120021,Kingsbridge Heights,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249118,9821451,80080,201177,2,BRONX,1175,1175,1175,GERARD AVENUE,35020,...,N,40.834706,-73.920721,4,16,197,2003002,2024880036,West Concourse,2013
7249177,9843516,57762,202376,2,BRONX,1142,1142,1142,COLLEGE AVENUE,20720,...,N,40.831147,-73.914322,4,16,175,2002258,2024340015,East Concourse-Concourse Village,2013
7249372,13637173,38773,111966,1,MANHATTAN,81,81,81,WEST 119 STREET,36150,...,Y,40.803494,-73.947148,10,9,200,1053292,1017180108,Central Harlem South,2020
7249735,14817349,31604,123410,1,MANHATTAN,421,421,423,WEST 24 STREET,34250,...,Y,40.747508,-74.001675,4,3,93,1012796,1007220024,Hudson Yards-Chelsea-Flatiron-Union Square,2022
7249736,14817350,31604,123410,1,MANHATTAN,421,421,423,WEST 24 STREET,34250,...,Y,40.747508,-74.001675,4,3,93,1012796,1007220024,Hudson Yards-Chelsea-Flatiron-Union Square,2022

In [31]:
fire_vio_per_bbl= fire_codes["BBL"].value_counts().reset_index().rename({"index":"BBL", "BBL":"hpd_fire_vio"}, axis = 1)


fire_vio_per_bbl

              BBL  hpd_fire_vio
0      1021370080            74
1      2037430063            55
2      1021380134            46
3      3049640040            44
4               0            43
...           ...           ...
18044  3018370067             1
18045  1014280028             1
18046  3020310058             1
18047  2028470063             1
18048  3035830035             1

[18049 rows x 2 columns]

In [38]:
#MERGE OF ALL AGGREGATE HPD VARIABLES PER BBL

hpd_agg_final = pd.merge(pd.merge(hpd_per_bbl,fire_vio_per_bbl,how = 'left',on='BBL'),violations_b_c_per_bbl,how = 'left', on='BBL')

hpd_agg_final

               BBL  num_hpd_vio  hpd_fire_vio  hpd_b_c_vio
0       3042719001         6411           5.0       4898.0
1                0         5450          43.0       3482.0
2       2024310026         4818          36.0       3712.0
3       5012720011         4170           NaN       2775.0
4       3013020001         4075          10.0       3257.0
...            ...          ...           ...          ...
181589  1019430052            1           NaN          NaN
181590  1012060017            1           NaN          NaN
181591  1018850049            1           NaN          NaN
181592  1012520050            1           NaN          NaN
181593  3011430042            1           NaN          NaN

[181594 rows x 4 columns]

In [39]:
hpd_agg_final = hpd_agg_final.fillna(0)

hpd_agg_final

               BBL  num_hpd_vio  hpd_fire_vio  hpd_b_c_vio
0       3042719001         6411           5.0       4898.0
1                0         5450          43.0       3482.0
2       2024310026         4818          36.0       3712.0
3       5012720011         4170           0.0       2775.0
4       3013020001         4075          10.0       3257.0
...            ...          ...           ...          ...
181589  1019430052            1           0.0          0.0
181590  1012060017            1           0.0          0.0
181591  1018850049            1           0.0          0.0
181592  1012520050            1           0.0          0.0
181593  3011430042            1           0.0          0.0

[181594 rows x 4 columns]

In [40]:
#export

hpd_agg_final.to_csv('hpd_agg_final.csv')

In [22]:
#count of inspections per year,census tract
hpd_per_census_tract = hpd_2012_2022_v2[['Borough','BoroID','CensusTract', 'InspectionDate']].groupby(['Borough','BoroID','CensusTract']).agg(['count'])

In [23]:
hpd_per_census_tract

                                 InspectionDate
                                          count
Borough       BoroID CensusTract
BRONX         2      2                     1444
                     4                     2249
                     16                    1529
                     19                    3119
                     20                    3078
...                                         ...
STATEN ISLAND 5      29104                  319
                     30301                  698
                     30302                 1031
                     31901                  504
                     31902                 5987

[2102 rows x 1 columns]

In [67]:
hpd_per_census_tract.to_csv('hpd_per_census_tract3.csv')

In [151]:
dob = pd.read_csv('/Users/bayerd01/Documents/ML CITIES/DOB_Violations.csv')

dob

/Users/bayerd01/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (3,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE
0,2552031,4,4023549.0,1085.0,00001,20210929,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
1,2336582,1,1008796.0,545.0,00015,20190405,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST
2,2551982,3,3390229.0,2327.0,00037,20210929,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
3,2513648,1,1001399.0,124.0,00004,20210302,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR
4,2551884,3,3115549.0,5043.0,00005,20210929,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242618,1572877,2,2008733.0,02873,00058,20110304,E,9027/375643,1419,SHAKESPEARE AVENUE,20130731.0,PVT: RESOLVED BY SATISFACTORY CAT 1 INSPECTION,002P5562,NaN,NaN,V*030411E9027/375643,V*-DOB VIOLATION - Resolved,E-ELEVATOR
2242619,1007533,1,1053367.0,01720,00054,20050131,LL6291,05025,14,MT. MORRIS PARK WEST,NaN,NaN,00813140,NaN,NaN,V013105LL629105025,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS
2242620,475117,5,5090047.0,01161,00150,19970210,LL6291,40698,150,GRANITE AVE,20040706.0,IRICIA DISMISSED FULL PENALTY PAID $500 ...,00815916,NaN,NaN,V*021097LL629140698,V*-DOB VIOLATION - DISMISSED,LL6291-LOCAL LAW 62/91 - BOILERS
2242621,1985620,3,3010557.0,00710,00001,20150720,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR
2242622,201753,3,3017951.0,00916,00049,19930816,LL6291,19539,855,NaN,NaN,NaN,00023508,NaN,NaN,V081693LL629119539,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS

In [152]:
#convert to datetime
dob['ISSUE_DATE']= pd.to_datetime(dob['ISSUE_DATE'], format='%Y%m%d', errors='coerce')

In [145]:
dob

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE
0,2552031,4,4023549.0,1085.0,00001,2021-09-29,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
1,2336582,1,1008796.0,545.0,00015,2019-04-05,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST
2,2551982,3,3390229.0,2327.0,00037,2021-09-29,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
3,2513648,1,1001399.0,124.0,00004,2021-03-02,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR
4,2551884,3,3115549.0,5043.0,00005,2021-09-29,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242618,1572877,2,2008733.0,02873,00058,2011-03-04,E,9027/375643,1419,SHAKESPEARE AVENUE,20130731.0,PVT: RESOLVED BY SATISFACTORY CAT 1 INSPECTION,002P5562,NaN,NaN,V*030411E9027/375643,V*-DOB VIOLATION - Resolved,E-ELEVATOR
2242619,1007533,1,1053367.0,01720,00054,2005-01-31,LL6291,05025,14,MT. MORRIS PARK WEST,NaN,NaN,00813140,NaN,NaN,V013105LL629105025,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS
2242620,475117,5,5090047.0,01161,00150,1997-02-10,LL6291,40698,150,GRANITE AVE,20040706.0,IRICIA DISMISSED FULL PENALTY PAID $500 ...,00815916,NaN,NaN,V*021097LL629140698,V*-DOB VIOLATION - DISMISSED,LL6291-LOCAL LAW 62/91 - BOILERS
2242621,1985620,3,3010557.0,00710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR
2242622,201753,3,3017951.0,00916,00049,1993-08-16,LL6291,19539,855,NaN,NaN,NaN,00023508,NaN,NaN,V081693LL629119539,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS

In [153]:
#create year column
dob['year'] = dob['ISSUE_DATE'].dt.year

In [40]:
max(dob['year'])

2230.0

In [154]:
#remove incorrect dates
years2 = [2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]

dob_2012_2022 = dob[dob.year.isin(years2)]

dob_2012_2022

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year
0,2552031,4,4023549.0,1085.0,00001,2021-09-29,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
1,2336582,1,1008796.0,545.0,00015,2019-04-05,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST,2019.0
2,2551982,3,3390229.0,2327.0,00037,2021-09-29,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
3,2513648,1,1001399.0,124.0,00004,2021-03-02,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2021.0
4,2551884,3,3115549.0,5043.0,00005,2021-09-29,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242610,2155772,4,4209845.0,09808,00014,2017-03-08,AEUHAZ1,00475,91-17,172 STREET,20171010.0,"JTR INV 13284096 PAID ON OCTOBER 6, 2017",NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35164577N,V*030817AEUHAZ100475,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2017.0
2242612,1685835,1,1028670.0,01126,00029,2012-06-13,AEUHAZ1,00050,135,CENTRAL PARK WEST,20140228.0,PAID 12609845,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,38221077Y,V*061312AEUHAZ100050,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2012.0
2242613,1919692,2,2049375.0,04317,00040,2014-12-21,E,9027/531377,2185,BOLTON STREET,20150713.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,002P1656,NaN,NaN,V*122114E9027/531377,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2014.0
2242615,2437373,2,2013811.0,03167,00001,2020-01-03,E,9027/668797,2501,GRAND CONCOURSE,20210304.0,PPN203 AOC SUB 020521 BY ARROW ELEV INC ...,2W12112,NaN,NaN,V*010320E9027/668797,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020.0
2242621,1985620,3,3010557.0,00710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015.0

In [155]:
#remove boro errors
boro = ['1','2','3','4','5']

dob_2012_2022 = dob[dob.BORO.isin(boro)]

dob_2012_2022

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year
0,2552031,4,4023549.0,1085.0,00001,2021-09-29,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
1,2336582,1,1008796.0,545.0,00015,2019-04-05,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST,2019.0
2,2551982,3,3390229.0,2327.0,00037,2021-09-29,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
3,2513648,1,1001399.0,124.0,00004,2021-03-02,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2021.0
4,2551884,3,3115549.0,5043.0,00005,2021-09-29,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242618,1572877,2,2008733.0,02873,00058,2011-03-04,E,9027/375643,1419,SHAKESPEARE AVENUE,20130731.0,PVT: RESOLVED BY SATISFACTORY CAT 1 INSPECTION,002P5562,NaN,NaN,V*030411E9027/375643,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2011.0
2242619,1007533,1,1053367.0,01720,00054,2005-01-31,LL6291,05025,14,MT. MORRIS PARK WEST,NaN,NaN,00813140,NaN,NaN,V013105LL629105025,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS,2005.0
2242620,475117,5,5090047.0,01161,00150,1997-02-10,LL6291,40698,150,GRANITE AVE,20040706.0,IRICIA DISMISSED FULL PENALTY PAID $500 ...,00815916,NaN,NaN,V*021097LL629140698,V*-DOB VIOLATION - DISMISSED,LL6291-LOCAL LAW 62/91 - BOILERS,1997.0
2242621,1985620,3,3010557.0,00710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015.0
2242622,201753,3,3017951.0,00916,00049,1993-08-16,LL6291,19539,855,NaN,NaN,NaN,00023508,NaN,NaN,V081693LL629119539,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS,1993.0

In [156]:
dob_2012_2022['BLOCK2'] = dob_2012_2022.BLOCK.str.replace('.' , '0')

dob_2012_2022

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1562069831.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  dob_2012_2022['BLOCK2'] = dob_2012_2022.BLOCK.str.replace('.' , '0')
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1562069831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BLOCK2'] = dob_2012_2022.BLOCK.str.replace('.' , '0')

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year,BLOCK2
0,2552031,4,4023549.0,1085.0,00001,2021-09-29,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0,NaN
1,2336582,1,1008796.0,545.0,00015,2019-04-05,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST,2019.0,NaN
2,2551982,3,3390229.0,2327.0,00037,2021-09-29,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0,NaN
3,2513648,1,1001399.0,124.0,00004,2021-03-02,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2021.0,NaN
4,2551884,3,3115549.0,5043.0,00005,2021-09-29,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242618,1572877,2,2008733.0,02873,00058,2011-03-04,E,9027/375643,1419,SHAKESPEARE AVENUE,20130731.0,PVT: RESOLVED BY SATISFACTORY CAT 1 INSPECTION,002P5562,NaN,NaN,V*030411E9027/375643,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2011.0,02873
2242619,1007533,1,1053367.0,01720,00054,2005-01-31,LL6291,05025,14,MT. MORRIS PARK WEST,NaN,NaN,00813140,NaN,NaN,V013105LL629105025,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS,2005.0,01720
2242620,475117,5,5090047.0,01161,00150,1997-02-10,LL6291,40698,150,GRANITE AVE,20040706.0,IRICIA DISMISSED FULL PENALTY PAID $500 ...,00815916,NaN,NaN,V*021097LL629140698,V*-DOB VIOLATION - DISMISSED,LL6291-LOCAL LAW 62/91 - BOILERS,1997.0,01161
2242621,1985620,3,3010557.0,00710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015.0,00710
2242622,201753,3,3017951.0,00916,00049,1993-08-16,LL6291,19539,855,NaN,NaN,NaN,00023508,NaN,NaN,V081693LL629119539,V-DOB VIOLATION - ACTIVE,LL6291-LOCAL LAW 62/91 - BOILERS,1993.0,00916

In [115]:
dob_2012_2022['BIN'] = dob_2012_2022['BIN'].fillna(0)
dob_2012_2022['BLOCK'] = dob_2012_2022['BLOCK'].fillna(0)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/3346480151.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BIN'] = dob_2012_2022['BIN'].fillna(0)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/3346480151.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BLOCK'] = dob_2012_2022['BLOCK'].fillna(0)

In [117]:
dob_2012_2022['BLOCK'] = dob_2012_2022.BLOCK.str.replace('V' , '0')

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/4152472326.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BLOCK'] = dob_2012_2022.BLOCK.str.replace('V' , '0')

In [119]:
dob_2012_2022 = dob_2012_2022.dropna(subset=['BLOCK'])

In [120]:
dob_2012_2022

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year
32768,2490960,3,3136699,05616,00027,2020-09-22,E,9028/689196,1256,45 STREET,20220118.0,PPN203 PVT AOC SUBMITTED BY HIGH RIDE ELEV CER...,3P11350,NaN,NaN,V*092220E9028/689196,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020.0
32769,2396693,2,2041897,03986,00005,2019-09-06,E,9027/661670,1554,ST PETERS AVENUE,20220118.0,PPN203 AOC SUB 011322 BY WARREN ELEV SERV CORP...,2F533,NaN,NaN,V*090619E9027/661670,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2019.0
32770,2570444,4,4213546,09966,00018,2022-01-18,C,22-00189,85-42,CHEVY CHASE STREET,NaN,NaN,NaN,WORK WITHOUT PERMIT. NOTED; AT REAR OF EXISTIN...,NaN,V011822C22-00189,V-DOB VIOLATION - ACTIVE,C-CONSTRUCTION,2022.0
32771,2560815,1,1036082,01294,00001,2021-12-01,EGRADE,2100714,761,5 AVENUE,20220118.0,CIANOW CRM Violation Dismissed,NaN,FAILURE TO DISPLAY ENERGY EFFICIENCY SCORE AND...,NaN,V*120121EGRADE2100714,V*-DOB VIOLATION - DISMISSED,EGRADE-FAILURE TO POST ENERGY GRADE/SCORE,2021.0
32772,2535537,3,3057758,02017,00030,2021-06-23,AEUHAZ1,00356,1166,FULTON STREET,20220118.0,000810 PAID INVOICE 90523516,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35536812Z,V*062321AEUHAZ100356,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242610,2155772,4,4209845,09808,00014,2017-03-08,AEUHAZ1,00475,91-17,172 STREET,20171010.0,"JTR INV 13284096 PAID ON OCTOBER 6, 2017",NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35164577N,V*030817AEUHAZ100475,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2017.0
2242612,1685835,1,1028670,01126,00029,2012-06-13,AEUHAZ1,00050,135,CENTRAL PARK WEST,20140228.0,PAID 12609845,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,38221077Y,V*061312AEUHAZ100050,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2012.0
2242613,1919692,2,2049375,04317,00040,2014-12-21,E,9027/531377,2185,BOLTON STREET,20150713.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,002P1656,NaN,NaN,V*122114E9027/531377,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2014.0
2242615,2437373,2,2013811,03167,00001,2020-01-03,E,9027/668797,2501,GRAND CONCOURSE,20210304.0,PPN203 AOC SUB 020521 BY ARROW ELEV INC ...,2W12112,NaN,NaN,V*010320E9027/668797,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020.0
2242621,1985620,3,3010557,00710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015.0

In [121]:
dob_2012_2022['BIN'] = dob_2012_2022['BIN'].astype(int)
dob_2012_2022['BLOCK'] = dob_2012_2022['BLOCK'].astype(int)
dob_2012_2022['year'] = dob_2012_2022['year'].astype(int)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1342132222.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BIN'] = dob_2012_2022['BIN'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1342132222.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BLOCK'] = dob_2012_2022['BLOCK'].astype(int)
/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/1342132222.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['year'] = dob_2012_2022['year'].astype(int)

In [125]:
#drop NAN values from block
dob_2012_2022 = dob_2012_2022.dropna(subset=['BORO'])

In [97]:
dob_2012_2022 = dob_2012_2022.dropna(subset=['LOT'])

In [126]:
dob_2012_2022

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year,BBL
32768,2490960,3,3136699,5616,00027,2020-09-22,E,9028/689196,1256,45 STREET,20220118.0,PPN203 PVT AOC SUBMITTED BY HIGH RIDE ELEV CER...,3P11350,NaN,NaN,V*092220E9028/689196,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020,3561600027
32769,2396693,2,2041897,3986,00005,2019-09-06,E,9027/661670,1554,ST PETERS AVENUE,20220118.0,PPN203 AOC SUB 011322 BY WARREN ELEV SERV CORP...,2F533,NaN,NaN,V*090619E9027/661670,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2019,2398600005
32770,2570444,4,4213546,9966,00018,2022-01-18,C,22-00189,85-42,CHEVY CHASE STREET,NaN,NaN,NaN,WORK WITHOUT PERMIT. NOTED; AT REAR OF EXISTIN...,NaN,V011822C22-00189,V-DOB VIOLATION - ACTIVE,C-CONSTRUCTION,2022,4996600018
32771,2560815,1,1036082,1294,00001,2021-12-01,EGRADE,2100714,761,5 AVENUE,20220118.0,CIANOW CRM Violation Dismissed,NaN,FAILURE TO DISPLAY ENERGY EFFICIENCY SCORE AND...,NaN,V*120121EGRADE2100714,V*-DOB VIOLATION - DISMISSED,EGRADE-FAILURE TO POST ENERGY GRADE/SCORE,2021,1129400001
32772,2535537,3,3057758,2017,00030,2021-06-23,AEUHAZ1,00356,1166,FULTON STREET,20220118.0,000810 PAID INVOICE 90523516,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35536812Z,V*062321AEUHAZ100356,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021,3201700030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242610,2155772,4,4209845,9808,00014,2017-03-08,AEUHAZ1,00475,91-17,172 STREET,20171010.0,"JTR INV 13284096 PAID ON OCTOBER 6, 2017",NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35164577N,V*030817AEUHAZ100475,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2017,4980800014
2242612,1685835,1,1028670,1126,00029,2012-06-13,AEUHAZ1,00050,135,CENTRAL PARK WEST,20140228.0,PAID 12609845,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,38221077Y,V*061312AEUHAZ100050,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2012,1112600029
2242613,1919692,2,2049375,4317,00040,2014-12-21,E,9027/531377,2185,BOLTON STREET,20150713.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,002P1656,NaN,NaN,V*122114E9027/531377,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2014,2431700040
2242615,2437373,2,2013811,3167,00001,2020-01-03,E,9027/668797,2501,GRAND CONCOURSE,20210304.0,PPN203 AOC SUB 020521 BY ARROW ELEV INC ...,2W12112,NaN,NaN,V*010320E9027/668797,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020,2316700001
2242621,1985620,3,3010557,710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015,371000001

In [79]:
dob_2012_2022_v2['LOT'].unique

<bound method Series.unique of 32768      00027
32769      00005
32770      00018
32771      00001
32772      00030
           ...
2242610    00014
2242612    00029
2242613    00040
2242615    00001
2242621    00001
Name: LOT, Length: 588237, dtype: object>

In [127]:
dob_2012_2022['BBL'] = dob_2012_2022['BORO'].map(str) + dob_2012_2022['BLOCK'].map(str) + dob_2012_2022['LOT'].map(str)

/var/folders/3p/wyw85mcd3r768npbh0ng8twwfvlvj0/T/ipykernel_58935/389065615.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dob_2012_2022['BBL'] = dob_2012_2022['BORO'].map(str) + dob_2012_2022['BLOCK'].map(str) + dob_2012_2022['LOT'].map(str)

In [128]:
max(dob_2012_2022['BBL'])

'`14900003'

In [54]:
dob_2012_2022

,ISN_DOB_BIS_VIOL,BORO,BIN,BLOCK,LOT,ISSUE_DATE,VIOLATION_TYPE_CODE,VIOLATION_NUMBER,HOUSE_NUMBER,STREET,DISPOSITION_DATE,DISPOSITION_COMMENTS,DEVICE_NUMBER,DESCRIPTION,ECB_NUMBER,NUMBER,VIOLATION_CATEGORY,VIOLATION_TYPE,year
0,2552031,4,4023549,0,00001,2021-09-29,AEUHAZ1,00513,91-02,23 AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35580654K,V092921AEUHAZ100513,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021
1,2336582,1,1008796,0,00015,2019-04-05,EVCAT1,00411,726,BROADWAY,20210928.0,CIANOW CRM Violation Dismissed,1W229,VIOLATION ISSUED TO ELEVATOR - FAILURE TO FILE...,NaN,V*040519EVCAT100411,V*-DOB VIOLATION - DISMISSED,EVCAT1-ELEVATOR ANNUAL INSPECTION / TEST,2019
2,2551982,3,3390229,0,00037,2021-09-29,AEUHAZ1,00464,131,NORTH 6 STREET,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,39043838R,V092921AEUHAZ100464,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021
3,2513648,1,1001399,0,00004,2021-03-02,E,9027/696734,9,PARK PL,20210929.0,PPN203 AOC SUB ON 9/23/21 BY:CENTENNIAL ...,1P15883,NaN,NaN,V*030221E9027/696734,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2021
4,2551884,3,3115549,0,00005,2021-09-29,AEUHAZ1,00366,1935,BEDFORD AVENUE,NaN,NaN,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35575335R,V092921AEUHAZ100366,V-DOB VIOLATION - ACTIVE,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2242610,2155772,4,4209845,9808,00014,2017-03-08,AEUHAZ1,00475,91-17,172 STREET,20171010.0,"JTR INV 13284096 PAID ON OCTOBER 6, 2017",NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,35164577N,V*030817AEUHAZ100475,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2017
2242612,1685835,1,1028670,1126,00029,2012-06-13,AEUHAZ1,00050,135,CENTRAL PARK WEST,20140228.0,PAID 12609845,NaN,FAILURE TO CERTIFY CORRECTION ON IMMEDIATELY H...,38221077Y,V*061312AEUHAZ100050,V*-DOB VIOLATION - DISMISSED,AEUHAZ1-FAIL TO CERTIFY CLASS 1,2012
2242613,1919692,2,2049375,4317,00040,2014-12-21,E,9027/531377,2185,BOLTON STREET,20150713.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,002P1656,NaN,NaN,V*122114E9027/531377,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2014
2242615,2437373,2,2013811,3167,00001,2020-01-03,E,9027/668797,2501,GRAND CONCOURSE,20210304.0,PPN203 AOC SUB 020521 BY ARROW ELEV INC ...,2W12112,NaN,NaN,V*010320E9027/668797,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2020
2242621,1985620,3,3010557,710,00001,2015-07-20,E,9027/550780,4014,1 AVENUE,20160727.0,PVT: SATISFIED BY SUBMISSION OF AOC FOR CAT 1 ...,003F3459,NaN,NaN,V*072015E9027/550780,V*-DOB VIOLATION - Resolved,E-ELEVATOR,2015

In [58]:
min(dob_2012_2022['BLOCK'])

0

In [ ]:
dob_2012_2022['BORO'].map(str) + df['Month'].map(str) + '-' + df['Year'].map(str)

In [ ]:
dob_2012_2022['BBL'] =

In [43]:
max(dob_2012_2022['ISSUE_DATE'])

Timestamp('2022-03-26 00:00:00')

In [56]:
#all dob violations - date filtered

dob_2012_2022.to_csv('dob_2012_2022_v2.csv')